In [4]:
# Assigning features and label variables
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [6]:
# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
wheather_encoded = le.fit_transform(weather)
print(wheather_encoded)


[[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]]
[2 2 0 1 1 1 0 2 2 1 2 0 0 1 1 1 1 2 0 0 0 2 0 2 2 2 1 2]


ValueError: Found array with dim 3. Estimator expected <= 2.

In [7]:
# Converting string labels into numbers
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)


[[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]]
[2 2 0 1 1 1 0 2 2 1 2 0 0 1 1 1 1 2 0 0 0 2 0 2 2 2 1 2]


ValueError: Found array with dim 3. Estimator expected <= 2.

In [8]:
#Combinig weather and temp into single listof tuples
features=zip(wheather_encoded,temp_encoded)
print(features)


[[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]]
[2 2 0 1 1 1 0 2 2 1 2 0 0 1 1 1 1 2 0 0 0 2 0 2 2 2 1 2]


ValueError: Found array with dim 3. Estimator expected <= 2.

In [23]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
import numpy as np

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
features = np.vstack((np.array(wheather_encoded), np.array(temp_encoded)))
features1 = np.hstack((np.array(wheather_encoded), np.array(temp_encoded)))
print(features)
print(features1)
features = features.transpose()
# print(features)
# print(label)
model.fit(features[:10,:],label[:10])

#Predict Output
predicted= model.predict([features[10:]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)


[[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]]
[2 2 0 1 1 1 0 2 2 1 2 0 0 1 1 1 1 2 0 0 0 2 0 2 2 2 1 2]


ValueError: Found array with dim 3. Estimator expected <= 2.